In [1]:
import numpy as np

In [2]:
# list型とndarray型は参照渡し。
a = [1, 2, 3]
b = a

a_ary = np.array([4, 5, 6])
b_ary = a_ary
print("List: ", a, b)
print("ndarray: ", a_ary, b_ary)

List:  [1, 2, 3] [1, 2, 3]
ndarray:  [4 5 6] [4 5 6]


In [3]:
a[0] = 5
a_ary[0] = 9
print("List: ", a, b)
print("ndarray: ", a_ary, b_ary)

List:  [5, 2, 3] [5, 2, 3]
ndarray:  [9 5 6] [9 5 6]


In [4]:
# コピーするには.copy()関数を用いる
a = [1, 2, 3]
b = a.copy()

a_ary = [4, 5, 6]
b_ary = a_ary.copy()

a[0] = 5
a_ary[0] = 9
print("List: ", a, b)
print("ndarray: ", a_ary, b_ary)

List:  [5, 2, 3] [1, 2, 3]
ndarray:  [9, 5, 6] [4, 5, 6]


In [5]:
# 連続したベクトルの生成
print(np.arange(10))
print(np.arange(5, 11))

[0 1 2 3 4 5 6 7 8 9]
[ 5  6  7  8  9 10]


In [6]:
# 行列の定義
x = np.array([[1, 2, 3],
              [4, 5, 6]])
print(x)
print(x[1, 2])
print(f"x.shape: {x.shape}") # 2行3列の行列

[[1 2 3]
 [4 5 6]]
6
x.shape: (2, 3)


In [7]:
# 行と列を個別に変数に格納できる
row, col = x.shape
print(f"x.shape: {row}, {col}")

x.shape: 2, 3


In [8]:
# 要素が0や1のndarray
zeros = np.zeros(10)
print(zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [9]:
ones = np.ones((2, 5))
print(ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [10]:
# 要素がランダムな行列の生成 0~1の一様分布から生成した行列。
np.random.rand(2, 3)

array([[0.22848624, 0.93351156, 0.24425389],
       [0.10102515, 0.23574441, 0.61195353]])

In [11]:
# *[], *()などで配列・タプルを展開して引数に渡せる
np.random.rand(*(2, 3))

array([[0.79817908, 0.59497586, 0.50907336],
       [0.67450456, 0.28013384, 0.70440897]])

In [12]:
# 平均0, 分散1のガウス分布
print(np.random.randn(5))
# 2から6までのランダムな整数値からなる2 * 2の行列
print(np.random.randint(2, 7, (2, 2)))

[ 1.0147614   0.48513236 -0.23517599  0.68001515  1.89658136]
[[3 6]
 [2 2]]


In [13]:
# 標準分布の出し方は2つある
# randn: 平均0, 分散1のガウス分布 2行5列
print(np.random.randn(2, 5))
# normal: 任意の平均(50)、標準偏差(2) 2行5列
print(np.random.normal(50, 2, (2, 5)))
# normal: 平均0, 標準偏差1, 2行5列
print(np.random.normal(size=(2, 5)))

[[ 1.74129064 -1.63346339  0.91185073  0.96980693 -1.34694099]
 [ 0.85187411  0.64576227  0.43058427 -0.10066652 -0.67786263]]
[[51.32482024 48.34316629 50.00657522 49.06126348 50.68376819]
 [55.05758586 48.57687564 52.56502588 49.62564755 50.58219213]]
[[ 1.37009296 -0.31211688 -0.53689961  1.18144453  1.59737152]
 [ 0.63857974  0.19098574  1.64688599 -0.49226605  0.28822295]]


In [14]:
# ソート
A = np.random.randn(2, 5)
print(A)
# sort
print(f"普通に行ごとにソート:\n{np.sort(A)}")
# argsortは各行でソートした結果の各要素順番を返す
sorted = np.argsort(A)
print(f"argsort 行ごとにソート:\n{sorted}")
# 特定の列の値をソート axis=0で列ごと、axis=1で行ごとにソート
sorted = np.argsort(A, axis=0)
print(f"argsort 列ごとにソート:\n{sorted}")

# argsortは3-practiceで使われている。以下その使われ方的な
A = np.random.randn(20, 5)
print(f"A:\n{A}")
# 2列目を取り出して降順にソート→インデックスが返される
inds = np.argsort(A[:, 2])[::-1]
print(f"inds:\n{inds}")
print("sorted by col=2")
for ind in inds:
    # 2列目が降順で表示される
    print(A[ind])
# インデックスでソートすると、何かと柔軟に使える。

[[ 2.23584152 -0.7895064  -0.26740435 -0.0228999   0.82724836]
 [-0.13875128  2.28348796  0.39977891  0.33764943  1.57324922]]
普通に行ごとにソート:
[[-0.7895064  -0.26740435 -0.0228999   0.82724836  2.23584152]
 [-0.13875128  0.33764943  0.39977891  1.57324922  2.28348796]]
argsort 行ごとにソート:
[[1 2 3 4 0]
 [0 3 2 4 1]]
argsort 列ごとにソート:
[[1 0 0 0 0]
 [0 1 1 1 1]]
A:
[[-0.96195632  0.04413108 -0.82185381 -1.65307578  1.42096116]
 [ 1.41723261 -0.41440911  0.5166565   1.68685652 -0.78740817]
 [ 0.82143478 -0.82506259  0.46164419  1.45875371 -0.46651467]
 [ 0.5217896  -0.28318206 -0.39680371 -0.65853426  0.18606447]
 [-0.92592447 -2.00932619 -0.26899343  1.17737674 -0.32689958]
 [-0.90859864 -0.01649446 -0.06528711  0.44718734  1.86489787]
 [ 1.57463898  0.84732246  1.67973216 -1.01913568 -0.78538335]
 [-0.42556079  0.21136288 -1.41067893  0.42227283 -0.53443289]
 [-0.38842102 -1.75340886  0.46577579  1.44355478  0.89722971]
 [ 0.25786544  0.20587097  0.19454716  0.92336181 -0.16693919]
 [-0.61790429

In [15]:
# 行列のサイズ変換
X = np.arange(10)
print(X)
X_reshape = X.reshape(2, 5)
print(X_reshape)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [16]:
# 2*5行列を1次元の行列に戻す
X_reshape.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
# 内積の計算
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[1, 1],
              [2, 2],
              [3, 3]])
print(A.dot(B))

[[14 14]
 [32 32]]


In [18]:
# 転置行列
print(A)
print(A.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [19]:
# スライシング: 要素の一部をまとめて表す
X = np.arange(10)
print(X)
# 0から5-1まで
print(X[:5])
# 5から最後まで
print(X[5:])
# 2から5-1まで
print(X[2:5])
# 0から最後まで、2刻みで
print(X[::2])
# 逆順に並び替え
print(X[::-1])

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]
[5 6 7 8 9]
[2 3 4]
[0 2 4 6 8]
[9 8 7 6 5 4 3 2 1 0]


In [20]:
# 多次元のスライシング
A = np.array([[1, 2, 3],
              [4, 5, 6]])
# 3列目だけを取り出す [行, 列]で指定
print(A[:, 2])
# 2列目だけを取り出す A[1]と同じ
print(A[1, :])

[3 6]
[4 5 6]


In [21]:
# 条件を満たすデータの書き換え
X = np.array([1, 1, 2, 3, 5, 6, 7])
X > 3

array([False, False, False, False,  True,  True,  True])

In [22]:
X[X > 3]

array([5, 6, 7])

In [23]:
# マスクを作って他の配列に適用できる
mask = X > 3
print(mask)
A = np.arange(7)
print(A)
print(A[mask])

[False False False False  True  True  True]
[0 1 2 3 4 5 6]
[4 5 6]
